/* CKW SMART GUARD MVP: browser-only demo data. Replace store functions with authenticated API calls in production. */
const state={user:null,view:'dashboard',incidents:[
 {id:'INC-240914-01',type:'ตรวจพบเหตุการณ์เสี่ยง',area:'อาคารเรียน 2',source:'Camera C-12',risk:'สูง',status:'รอตรวจสอบ',time:'10:39'},
 {id:'INC-240914-02',type:'ค่าผิดปกติจากเซนเซอร์',area:'ทางเดินหลังอาคาร',source:'IoT S-04',risk:'ปานกลาง',status:'รอตรวจสอบ',time:'10:31'},
 {id:'INC-240914-03',type:'แจ้งเตือนการเข้าพื้นที่',area:'ประตูทิศเหนือ',source:'Camera C-02',risk:'ต่ำ',status:'ตรวจสอบแล้ว',time:'09:12'}
],tips:[{id:'TIP-8K2M',category:'ความปลอดภัย',urgency:'สูง',time:'09:58',status:'ใหม่',text:'มีจุดที่ควรให้ครูตรวจสอบบริเวณอาคารเรียน 2'}],devices:[{id:'C-12',name:'Camera อาคารเรียน 2',kind:'IP Camera',status:'ออนไลน์',last:'10:42'},{id:'S-04',name:'Sensor ทางเดินหลังอาคาร',kind:'Motion sensor',status:'ออนไลน์',last:'10:41'},{id:'C-02',name:'Camera ประตูทิศเหนือ',kind:'IP Camera',status:'ออฟไลน์',last:'09:25'}]};
const el=document.querySelector('#app');
const esc=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const riskClass=r=>r==='สูง'?'danger':r==='ปานกลาง'?'warning':'good';
function shell(content){const nav=[['dashboard','ภาพรวม'],['incidents','เหตุการณ์'],['tips','เบาะแส'],['heatmap','แผนที่จุดเสี่ยง'],['reports','รายงาน'],['devices','อุปกรณ์'],['settings','ตั้งค่าระบบ']];el.innerHTML=`<div class="shell"><header class="topbar"><div class="brand"><span class="brand-mark">⌂</span>CKW SMART GUARD</div><div class="live">● เฝ้าระวังแบบเรียลไทม์</div><div class="profile">ครูผู้รับผิดชอบ · <button class="btn secondary" onclick="logout()">ออกจากระบบ</button></div></header><div class="layout"><aside class="sidebar">${nav.map(([id,label])=>`<button class="nav-button ${state.view===id?'active':''}" onclick="go('${id}')">${label}</button>`).join('')}</aside><section class="content">${content}</section></div></div>`}
function dashboard(){const pending=state.incidents.filter(x=>x.status==='รอตรวจสอบ').length; shell(`<h1>ภาพรวมความปลอดภัย</h1><p class="subtitle">อัปเดตล่าสุด 10:42 น. · วันนี้ 14 กันยายน</p><div class="grid stats"><div class="card"><div class="stat-label">เหตุการณ์วันนี้</div><div class="stat-value">${state.incidents.length+9}</div></div><div class="card"><div class="stat-label">รอตรวจสอบ</div><div class="stat-value danger">${pending}</div></div><div class="card"><div class="stat-label">ระดับสูง</div><div class="stat-value warning">${state.incidents.filter(x=>x.risk==='สูง').length}</div></div><div class="card"><div class="stat-label">อุปกรณ์พร้อมใช้</div><div class="stat-value good">${state.devices.filter(x=>x.status==='ออนไลน์').length}/${state.devices.length}</div></div></div><div class="grid split"><section class="card"><div class="panel-title"><h2>ต้องตรวจสอบ</h2><span class="pill">${pending} รายการ</span></div>${state.incidents.slice(0,3).map((x,i)=>`<div class="event"><span class="dot ${i===1?'warn':''}"></span><div><b>${esc(x.type)}</b><small>${esc(x.area)} · ${esc(x.source)} · ${esc(x.status)}</small></div><time>${x.time}</time></div>`).join('')}<div class="actions"><button class="btn" onclick="go('incidents')">เปิดคิวเหตุการณ์</button></div></section><section class="card"><div class="panel-title"><h2>Heatmap พื้นที่</h2><span class="pill">7 วัน</span></div><div class="heatmap">${['','m','','h','','m','h','x','h','','','m','h','m',''].map(c=>`<span class="heat-cell ${c}"></span>`).join('')}</div><div class="legend"><span>ต่ำ</span><span>ปานกลาง</span><span class="hi">สูง</span><span class="urgent">เร่งด่วน</span></div><div class="actions"><button class="btn secondary" onclick="go('heatmap')">ดูแผนที่เต็ม</button></div></section></div>`)}
function incidents(){shell(`<div class="toolbar"><div><h1>เหตุการณ์และการแจ้งเตือน</h1><p class="subtitle">เจ้าหน้าที่ต้องตรวจสอบก่อนปิดเหตุการณ์ทุกครั้ง</p></div><button class="btn" onclick="newIncident()">+ สร้างเหตุการณ์</button></div><div class="card"><div class="filters"><select id="risk-filter" onchange="renderIncidents()"><option value="">ทุกระดับความเสี่ยง</option><option>สูง</option><option>ปานกลาง</option><option>ต่ำ</option></select><select id="status-filter" onchange="renderIncidents()"><option value="">ทุกสถานะ</option><option>รอตรวจสอบ</option><option>ตรวจสอบแล้ว</option></select></div><div class="table-wrap"><table class="table"><thead><tr><th>รหัส</th><th>เหตุการณ์</th><th>พื้นที่/แหล่งข้อมูล</th><th>ความเสี่ยง</th><th>สถานะ</th><th></th></tr></thead><tbody id="incident-rows"></tbody></table></div></div>`);renderIncidents()}
function renderIncidents(){const r=document.querySelector('#risk-filter')?.value||'',s=document.querySelector('#status-filter')?.value||'';const rows=state.incidents.filter(x=>(!r||x.risk===r)&&(!s||x.status===s)).map(x=>`<tr><td>${x.id}<br><span class="muted">${x.time}</span></td><td><b>${esc(x.type)}</b></td><td>${esc(x.area)}<br><span class="muted">${esc(x.source)}</span></td><td><span class="risk ${riskClass(x.risk)}">${x.risk}</span></td><td><span class="status ${x.status==='รอตรวจสอบ'?'pending':''}">${x.status}</span></td><td><button class="btn secondary" onclick="incidentDetail('${x.id}')">ตรวจสอบ</button></td></tr>`).join('');document.querySelector('#incident-rows').innerHTML=rows||'<tr><td colspan="6" class="empty">ไม่พบเหตุการณ์ตามตัวกรอง</td></tr>'}
function incidentDetail(id){const x=state.incidents.find(a=>a.id===id);shell(`<button class="btn secondary" onclick="go('incidents')">← กลับรายการ</button><div class="toolbar" style="margin-top:18px"><div><h1>${esc(x.type)}</h1><p class="subtitle">${x.id} · ${x.time} น. · ${esc(x.area)}</p></div><span class="status ${x.status==='รอตรวจสอบ'?'pending':''}">${x.status}</span></div><div class="grid split"><section class="card"><h2>ข้อมูลเหตุการณ์</h2><div class="timeline"><div class="timeline-item"><b>ระบบรับข้อมูลจาก ${esc(x.source)}</b><br><span class="muted">เวลา ${x.time} น.</span></div><div class="timeline-item"><b>ระบบจัดระดับความเสี่ยง: ${x.risk}</b><br><span class="muted">ผลจากระบบต้องได้รับการตรวจสอบโดยเจ้าหน้าที่</span></div><div class="timeline-item"><b>สร้างรายการในคิวตรวจสอบ</b></div></div><div class="actions">${x.status==='รอตรวจสอบ'?`<button class="btn" onclick="resolve('${x.id}','ตรวจสอบแล้ว')">ยืนยันและปิดเหตุการณ์</button><button class="btn secondary" onclick="resolve('${x.id}','ไม่ใช่เหตุการณ์')">ไม่ใช่เหตุการณ์</button>`:''}</div></section><aside class="card"><h2>หลักฐาน</h2><p class="notice">สื่อหลักฐานจริงแสดงเฉพาะผู้มีสิทธิ์ และไม่ควรเผยแพร่ภายนอกระบบ</p><p class="muted">ในโหมดต้นแบบยังไม่มีการเชื่อมต่อ object storage ของกล้อง</p></aside></div>`)}
function tips(){shell(`<div class="toolbar"><div><h1>เบาะแสแบบไม่ระบุตัวตน</h1><p class="subtitle">คัดกรองโดยเจ้าหน้าที่ ไม่ใช้ข้อความเพื่อตัดสินบุคคลโดยอัตโนมัติ</p></div><button class="btn" onclick="tipForm()">+ รับเบาะแส</button></div>${state.tips.map(x=>`<section class="card tip-card"><div class="panel-title"><h2>${x.id} · ${x.category}</h2><span class="status urgent">เร่งด่วน: ${x.urgency}</span></div><p>${esc(x.text)}</p><p class="muted">รับเมื่อ ${x.time} น. · สถานะ ${x.status}</p><button class="btn secondary" onclick="alert('บันทึกการมอบหมาย (โหมดต้นแบบ)')">มอบหมายเจ้าหน้าที่</button></section>`).join('')}`)}
function tipForm(){shell(`<button class="btn secondary" onclick="go('tips')">← กลับ</button><div class="form"><h1 style="margin-top:20px">รับเบาะแส</h1><p class="subtitle">แบบฟอร์มต้นแบบสำหรับเจ้าหน้าที่; หน้าสาธารณะต้องแยกโดเมนและไม่บันทึกตัวระบุตนโดยไม่จำเป็น</p><div class="notice">หากมีอันตรายเร่งด่วน ให้ติดต่อครูเวรหรือหน่วยฉุกเฉินโดยตรง</div><div class="card"><div class="field"><label>หมวดหมู่</label><select id="tip-category"><option>ความปลอดภัย</option><option>ความเป็นอยู่</option><option>ทรัพย์สิน</option></select></div><div class="field"><label>ระดับความเร่งด่วน</label><select id="tip-urgency"><option>ต่ำ</option><option>ปานกลาง</option><option>สูง</option></select></div><div class="field"><label>รายละเอียด</label><textarea id="tip-text" rows="5" placeholder="ระบุสิ่งที่พบ พื้นที่ และเวลาคร่าว ๆ โดยไม่ต้องเปิดเผยข้อมูลส่วนตัว"></textarea></div><button class="btn" onclick="submitTip()">บันทึกเบาะแส</button></div></div>`)}
function heatmap(){shell(`<h1>แผนที่จุดเสี่ยง</h1><p class="subtitle">ข้อมูลสรุประดับพื้นที่ ไม่แสดงข้อมูลบุคคลในหน้านี้</p><section class="card"><div class="panel-title"><h2>อาคารเรียน 2</h2><span class="pill">14 เหตุการณ์ / 7 วัน</span></div><div class="heatmap" style="max-width:540px">${['','m','h','','','m','h','x','h','','','m','h','m',''].map(c=>`<span class="heat-cell ${c}"></span>`).join('')}</div><div class="legend"><span>ต่ำ</span><span>ปานกลาง</span><span class="hi">สูง</span><span class="urgent">เร่งด่วน</span></div><p class="micro">ก่อนใช้แผนที่จริง ให้กำหนดตำแหน่งกล้องและโซนจากผังโรงเรียนที่ได้รับอนุญาต และตรวจสอบว่า Heatmap ไม่ชี้นำให้ระบุตัวนักเรียน</p></section>`)}
function reports(){shell(`<h1>รายงาน</h1><p class="subtitle">สรุปเพื่อการตัดสินใจ โดยใช้ข้อมูลน้อยที่สุดที่จำเป็น</p><div class="grid stats"><div class="card"><div class="stat-label">เหตุการณ์ 7 วัน</div><div class="stat-value">41</div></div><div class="card"><div class="stat-label">เวลาตอบสนองเฉลี่ย</div><div class="stat-value">4.2 นาที</div></div><div class="card"><div class="stat-label">แจ้งเตือนที่ยืนยัน</div><div class="stat-value good">78%</div></div><div class="card"><div class="stat-label">False alarm</div><div class="stat-value warning">12%</div></div></div><section class="card" style="margin-top:16px"><h2>ก่อนส่งออกรายงาน</h2><p class="muted">ระบบจริงต้องตรวจสอบสิทธิ์ บันทึก audit log และเลือกปกปิดข้อมูลส่วนบุคคลตามวัตถุประสงค์ของรายงาน</p><button class="btn secondary" onclick="alert('การส่งออกถูกปิดในโหมดต้นแบบ')">ส่งออกรายงาน</button></section>`)}
function devices(){shell(`<h1>กล้องและอุปกรณ์ IoT</h1><p class="subtitle">ตรวจสอบความพร้อมก่อนใช้ข้อมูลในการแจ้งเตือน</p><section class="card"><div class="table-wrap"><table class="table"><thead><tr><th>รหัส</th><th>อุปกรณ์</th><th>ประเภท</th><th>สถานะ</th><th>ติดต่อครั้งล่าสุด</th></tr></thead><tbody>${state.devices.map(x=>`<tr><td>${x.id}</td><td><b>${x.name}</b></td><td>${x.kind}</td><td><span class="status ${x.status==='ออฟไลน์'?'urgent':''}">${x.status}</span></td><td>${x.last}</td></tr>`).join('')}</tbody></table></div></section>`)}
function settings(){shell(`<h1>ตั้งค่าระบบ</h1><p class="subtitle">กำหนดโดยผู้ดูแลระบบเท่านั้น</p><section class="card"><h2>กฎแจ้งเตือน</h2><p class="muted">เมื่อเหตุการณ์ระดับสูงถูกตรวจพบ ให้ส่งเข้าคิวเจ้าหน้าที่และแจ้งผ่าน LINE ภายใน 60 วินาทีหลังตรวจสอบการตั้งค่าแล้ว</p><button class="btn secondary" onclick="alert('การแก้ไขถูกจำลองในต้นแบบ')">แก้ไขกฎ</button></section><section class="card" style="margin-top:16px"><h2>Audit log</h2><p class="muted">ระบบ production ต้องบันทึกการเข้าสู่ระบบ การเปิดหลักฐาน การเปลี่ยนสถานะ และการส่งออกรายงาน โดยป้องกันการแก้ไขย้อนหลัง</p></section>`)}
function newIncident(){const id=`INC-${Date.now().toString().slice(-6)}`;state.incidents.unshift({id,type:'เหตุการณ์ที่บันทึกโดยเจ้าหน้าที่',area:'ยังไม่ระบุ',source:'Manual',risk:'ต่ำ',status:'รอตรวจสอบ',time:new Date().toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'})});incidents()}
function resolve(id,status){state.incidents.find(x=>x.id===id).status=status;incidentDetail(id)}
function submitTip(){const text=document.querySelector('#tip-text').value.trim();if(!text)return alert('กรุณาระบุรายละเอียด');const id='TIP-'+Math.random().toString(36).slice(2,6).toUpperCase();state.tips.unshift({id,category:document.querySelector('#tip-category').value,urgency:document.querySelector('#tip-urgency').value,time:'เมื่อสักครู่',status:'ใหม่',text});go('tips')}
function go(view){state.view=view;({dashboard,incidents,tips,heatmap,reports,devices,settings}[view])()}
function login(){el.innerHTML=`<div class="login"><section class="card login-box"><div class="brand"><span class="brand-mark">⌂</span>CKW SMART GUARD</div><h1>เข้าสู่ระบบเจ้าหน้าที่</h1><p class="subtitle">ใช้บัญชีที่ได้รับอนุญาตจากสถานศึกษา</p><div class="field"><label>อีเมลโรงเรียน</label><input type="email" value="staff@ckw.ac.th"></div><div class="field"><label>รหัสผ่าน</label><input type="password" value="demo"></div><button class="btn" onclick="state.user='staff';go('dashboard')">เข้าสู่ระบบ (ต้นแบบ)</button><p class="micro">ระบบจริงต้องใช้ SSO/MFA, RBAC, session timeout และบันทึก audit log</p></section></div>`}
function logout(){state.user=null;login()} login();
